title: Wix Editor Onboarding
description: Onboarding for new devs
steps:
  - course: 'https://github.com/wix-private/santa-editor'
    description: The first step in your course
    title: 'Clone, build and run editor locally'
    link: 'https://github.com/wix-private/santa-editor'
  - link: 'https://lab.github.com'
    title: Product Overview
    description: schedule a meeting with a product manager
  - title: schedule a meeting with a UX designer
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
    course: UX overview
  - title: BA / BI overview
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
    course: ''
    description: Schedule a meeting with an analyst
    link: ''
  - title: Learn more about how browsers work under the hood
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
    link: 'https://www.youtube.com/watch?v=r9k8p-bs4iQ'
    description: 'Watch this video as inspiration, but there is a lot more to learn'
    video: 'https://www.youtube.com/watch?v=r9k8p-bs4iQ'
